version: "3.8"

services:
  api:
    image: seleris-api
    container_name: seleris-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: seleris-redis
    ports:
      - "6379:6379"