name: CI - Healthcare API

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    env:
      NODE_ENV: test
      JWT_SECRET_KEY: testsecret
      JWT_REFRESH_SECRET_KEY: testrefresh
      JWT_EXPIRES_IN: 3600
      JWT_REFRESH_EXPIRES_IN: 86400
      SALT: 10

      MONGO_CLUSTER_URI: mongodb://127.0.0.1:27017
      MONGO_DB: healthcare_test

      REDIS_DISABLED: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run test
